// src/core/constants/defaultIconTheme.ts
const defaultThemeMap = {
  // ──────────────────────────────────────────────────────────────────────────
  // Extensions
  // ──────────────────────────────────────────────────────────────────────────
  extensions: {

    // ── Web ──────────────────────────────────────────────────────────────
    'html': 'icon-html',       'htm': 'icon-html',
    'xhtml': 'icon-html',      'html5': 'icon-html',
    'css': 'icon-css',
    'scss': 'icon-sass',       'sass': 'icon-sass',
    'less': 'icon-less',
    'styl': 'icon-stylus',     'stylus': 'icon-stylus',
    'pcss': 'icon-postcss',
    'js': 'icon-js',           'mjs': 'icon-js',      'cjs': 'icon-js',
    'jsx': 'icon-jsx',
    'ts': 'icon-ts',
    'tsx': 'icon-tsx',
    'vue': 'icon-vue',
    'svelte': 'icon-svelte',
    'astro': 'icon-astro',

    // ── Backend ──────────────────────────────────────────────────────────
    'py': 'icon-python',       'pyw': 'icon-python',  'pyc': 'icon-python',
    'pyi': 'icon-python',      'pyd': 'icon-python',
    'java': 'icon-java',       'class': 'icon-java',  'jar': 'icon-java',
    'kt': 'icon-kotlin',       'kts': 'icon-kotlin',
    'scala': 'icon-scala',     'sc': 'icon-scala',
    'groovy': 'icon-groovy',   'gradle': 'icon-gradle',
    'c': 'icon-c',             'h': 'icon-c',
    'cpp': 'icon-cpp',         'cc': 'icon-cpp',      'cxx': 'icon-cpp',
    'c++': 'icon-cpp',         'hh': 'icon-cpp',      'hpp': 'icon-cpp',
    'hxx': 'icon-cpp',
    'cs': 'icon-csharp',       'csx': 'icon-csharp',
    'fs': 'icon-fsharp',       'fsx': 'icon-fsharp',  'fsi': 'icon-fsharp',
    'vb': 'icon-vb',
    'go': 'icon-go',
    'rs': 'icon-rust',
    'rb': 'icon-ruby',         'erb': 'icon-ruby',    'rake': 'icon-ruby',
    'php': 'icon-php',         'php3': 'icon-php',    'php4': 'icon-php',
    'php5': 'icon-php',        'phtml': 'icon-php',
    'pl': 'icon-perl',         'pm': 'icon-perl',     'pod': 'icon-perl',
    'lua': 'icon-lua',
    'r': 'icon-r',             'rmd': 'icon-r',
    'swift': 'icon-swift',
    'dart': 'icon-dart',
    'ex': 'icon-elixir',       'exs': 'icon-elixir',  'heex': 'icon-elixir',
    'erl': 'icon-erlang',      'hrl': 'icon-erlang',
    'hs': 'icon-haskell',      'lhs': 'icon-haskell',
    'clj': 'icon-clojure',     'cljs': 'icon-clojure', 'cljc': 'icon-clojure',
    'ml': 'icon-ocaml',        'mli': 'icon-ocaml',   'mll': 'icon-ocaml',
    'nim': 'icon-nim',         'nims': 'icon-nim',
    'zig': 'icon-zig',
    'cr': 'icon-crystal',
    'jl': 'icon-julia',
    'd': 'icon-d',             'di': 'icon-d',
    'cob': 'icon-cobol',       'cbl': 'icon-cobol',
    'f90': 'icon-fortran',     'f95': 'icon-fortran', 'f03': 'icon-fortran',
    'pas': 'icon-pascal',      'pp': 'icon-pascal',

    // ── Shell / Scripts ──────────────────────────────────────────────────
    'sh': 'icon-bash',         'bash': 'icon-bash',   'zsh': 'icon-bash',
    'fish': 'icon-fish',
    'bat': 'icon-bat',         'cmd': 'icon-bat',
    'ps1': 'icon-powershell',  'psm1': 'icon-powershell', 'psd1': 'icon-powershell',

    // ── Low Level ────────────────────────────────────────────────────────
    'wasm': 'icon-wasm',
    'wat': 'icon-wasm',
    'asm': 'icon-asm',         's': 'icon-asm',

    // ── Data / Config ────────────────────────────────────────────────────
    'json': 'icon-json',       'json5': 'icon-json',  'jsonc': 'icon-json',
    'yaml': 'icon-yaml',       'yml': 'icon-yaml',
    'toml': 'icon-toml',
    'xml': 'icon-xml',         'xsl': 'icon-xml',     'xsd': 'icon-xml',
    'wxml': 'icon-xml',
    'csv': 'icon-csv',         'tsv': 'icon-tsv',
    'ini': 'icon-ini',
    'conf': 'icon-conf',       'config': 'icon-config',
    'env': 'icon-env',
    'properties': 'icon-properties',
    'prisma': 'icon-prisma',
    'graphql': 'icon-graphql', 'gql': 'icon-graphql',
    'proto': 'icon-proto',
    'sql': 'icon-sql',         'mysql': 'icon-sql',
    'sqlite': 'icon-sqlite',   'db': 'icon-sqlite',
    'pgsql': 'icon-pgsql',     'psql': 'icon-pgsql',

    // ── Docs ─────────────────────────────────────────────────────────────
    'md': 'icon-markdown',     'markdown': 'icon-markdown',
    'mdx': 'icon-mdx',
    'rst': 'icon-rst',
    'txt': 'icon-txt',         'text': 'icon-txt',
    'pdf': 'icon-pdf',
    'tex': 'icon-tex',         'latex': 'icon-tex',   'ltx': 'icon-tex',
    'adoc': 'icon-asciidoc',   'asciidoc': 'icon-asciidoc',
    'org': 'icon-org',

    // ── Version Control ──────────────────────────────────────────────────
    'patch': 'icon-patch',
    'diff': 'icon-diff',

    // ── Images ───────────────────────────────────────────────────────────
    'png': 'icon-image',       'jpg': 'icon-image',   'jpeg': 'icon-image',
    'gif': 'icon-image',       'bmp': 'icon-image',   'webp': 'icon-image',
    'ico': 'icon-ico',         'tiff': 'icon-image',  'tif': 'icon-image',
    'heic': 'icon-image',      'heif': 'icon-image',  'avif': 'icon-image',
    'svg': 'icon-svg-file',
    'psd': 'icon-psd',
    'ai': 'icon-ai',
    'xd': 'icon-xd',
    'sketch': 'icon-sketch',
    'fig': 'icon-figma',

    // ── Media ────────────────────────────────────────────────────────────
    'mp3': 'icon-audio',       'ogg': 'icon-audio',   'wav': 'icon-audio',
    'flac': 'icon-audio',      'aac': 'icon-audio',   'm4a': 'icon-audio',
    'opus': 'icon-audio',
    'mp4': 'icon-video',       'mov': 'icon-video',   'avi': 'icon-video',
    'mkv': 'icon-video',       'webm': 'icon-video',  'm4v': 'icon-video',
    'wmv': 'icon-video',       'flv': 'icon-video',
    'ttf': 'icon-font',        'otf': 'icon-font',    'woff': 'icon-font',
    'woff2': 'icon-font',      'eot': 'icon-font',

    // ── Archives ─────────────────────────────────────────────────────────
    'zip': 'icon-zip',         'tar': 'icon-tar',     'gz': 'icon-gz',
    'tgz': 'icon-gz',          'bz2': 'icon-gz',      'xz': 'icon-gz',
    'rar': 'icon-rar',         '7z': 'icon-7z',       'zst': 'icon-zip',
    'apk': 'icon-apk',         'aab': 'icon-apk',
    'exe': 'icon-exe',         'msi': 'icon-exe',
    'dmg': 'icon-dmg',         'pkg': 'icon-dmg',
    'deb': 'icon-deb',         'rpm': 'icon-rpm',
    'appimage': 'icon-appimage',

    // ── Notebooks ────────────────────────────────────────────────────────
    'ipynb': 'icon-jupyter',

    // ── Certs / Keys ─────────────────────────────────────────────────────
    'pem': 'icon-pem',         'key': 'icon-key',     'crt': 'icon-cert',
    'cer': 'icon-cert',        'csr': 'icon-csr',     'p12': 'icon-cert',
    'pfx': 'icon-cert',        'p8': 'icon-key',

    // ── Extra Languages / New Additions ──────────────────────────────────
    'abap': 'icon-abap',
    'aes': 'icon-aes',
    'cls': 'icon-apex',
    'dats': 'icon-ats',        'sats': 'icon-ats',
    'azcli': 'icon-azure',
    'bicep': 'icon-bicep',
    'mligo': 'icon-cameligo',
    'coffee': 'icon-coffee',
    'csp': 'icon-csp',
    'cyp': 'icon-cypher',      'cypher': 'icon-cypher',
    'dax': 'icon-dax',
    'ecl': 'icon-ecl',
    'flow': 'icon-flow',
    'hbs': 'icon-handlebars',  'handlebars': 'icon-handlebars',
    'lex': 'icon-lexon',
    'liquid': 'icon-liquid',
    'mips': 'icon-mips',
    'm3': 'icon-m3',           'ig': 'icon-m3',       'mg': 'icon-m3',
    'm': 'icon-objc',
    'ligo': 'icon-pascaligo',
    'pla': 'icon-pla',
    'pq': 'icon-powerquery',
    'pug': 'icon-pug',
    'qs': 'icon-qsharp',
    'cshtml': 'icon-razor',
    'redis': 'icon-redis',
    'scm': 'icon-scheme',      'ss': 'icon-scheme',
    'sb': 'icon-smallbasic',
    'sol': 'icon-solidity',
    'rq': 'icon-sparql',       'sparql': 'icon-sparql',
    'st': 'icon-st',
    'sv': 'icon-systemverilog',
    'tcl': 'icon-tcl',
    'twig': 'icon-twig',
    'tsp': 'icon-typespec',
    'v': 'icon-v',
    'wgsl': 'icon-wgsl',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Exact File Names  (case-insensitive, checked BEFORE extension)
  // ──────────────────────────────────────────────────────────────────────────
  fileNames: {

    // ── Git ──────────────────────────────────────────────────────────────
    '.gitignore': 'icon-gitignore',
    '.gitattributes': 'icon-gitattributes',
    '.gitmodules': 'icon-gitmodules',
    '.gitkeep': 'icon-gitkeep',
    '.gitmessage': 'icon-git',
    '.mailmap': 'icon-git',

    // ── Editor Config ────────────────────────────────────────────────────
    '.editorconfig': 'icon-editorconfig',

    // ── Env Files ────────────────────────────────────────────────────────
    '.env': 'icon-env',
    '.env.local': 'icon-env',
    '.env.development': 'icon-env',
    '.env.production': 'icon-env',
    '.env.test': 'icon-env',
    '.env.staging': 'icon-env',
    '.env.example': 'icon-env',
    '.env.sample': 'icon-env',

    // ── Node / npm ───────────────────────────────────────────────────────
    'package.json': 'icon-npm',
    'package-lock.json': 'icon-npm',
    '.npmrc': 'icon-npm',
    '.npmignore': 'icon-npm',
    '.nvmrc': 'icon-node',
    '.node-version': 'icon-node',

    // ── Yarn / pnpm / bun ────────────────────────────────────────────────
    'yarn.lock': 'icon-yarn',
    '.yarnrc': 'icon-yarn',
    '.yarnrc.yml': 'icon-yarn',
    'pnpm-lock.yaml': 'icon-pnpm',
    'pnpm-workspace.yaml': 'icon-pnpm',
    '.pnpmfile.cjs': 'icon-pnpm',
    'bun.lockb': 'icon-bun',
    'bunfig.toml': 'icon-bun',

    // ── TypeScript Config ─────────────────────────────────────────────────
    'tsconfig.json': 'icon-tsconfig',
    'tsconfig.base.json': 'icon-tsconfig',
    'tsconfig.build.json': 'icon-tsconfig',
    'tsconfig.app.json': 'icon-tsconfig',
    'tsconfig.node.json': 'icon-tsconfig',
    'jsconfig.json': 'icon-tsconfig',

    // ── Lint / Format ────────────────────────────────────────────────────
    '.eslintrc': 'icon-eslint',
    '.eslintrc.js': 'icon-eslint',
    '.eslintrc.cjs': 'icon-eslint',
    '.eslintrc.mjs': 'icon-eslint',
    '.eslintrc.json': 'icon-eslint',
    '.eslintrc.yml': 'icon-eslint',
    '.eslintrc.yaml': 'icon-eslint',
    'eslint.config.js': 'icon-eslint',
    'eslint.config.cjs': 'icon-eslint',
    'eslint.config.mjs': 'icon-eslint',
    '.eslintignore': 'icon-eslint',
    '.prettierrc': 'icon-prettier',
    '.prettierrc.js': 'icon-prettier',
    '.prettierrc.cjs': 'icon-prettier',
    '.prettierrc.json': 'icon-prettier',
    '.prettierrc.yml': 'icon-prettier',
    '.prettierrc.yaml': 'icon-prettier',
    '.prettierrc.toml': 'icon-prettier',
    'prettier.config.js': 'icon-prettier',
    'prettier.config.cjs': 'icon-prettier',
    '.prettierignore': 'icon-prettier',
    '.stylelintrc': 'icon-stylelint',
    '.stylelintrc.json': 'icon-stylelint',
    'stylelint.config.js': 'icon-stylelint',
    'biome.json': 'icon-biome',
    'biome.jsonc': 'icon-biome',

    // ── Build Tools ──────────────────────────────────────────────────────
    'vite.config.js': 'icon-vite',
    'vite.config.ts': 'icon-vite',
    'vite.config.mjs': 'icon-vite',
    'webpack.config.js': 'icon-webpack',
    'webpack.config.ts': 'icon-webpack',
    'webpack.config.mjs': 'icon-webpack',
    'rollup.config.js': 'icon-rollup',
    'rollup.config.ts': 'icon-rollup',
    'rollup.config.mjs': 'icon-rollup',
    'esbuild.config.js': 'icon-esbuild',
    '.swcrc': 'icon-swc',
    'babel.config.js': 'icon-babel',
    'babel.config.json': 'icon-babel',
    'babel.config.cjs': 'icon-babel',
    '.babelrc': 'icon-babel',
    '.babelrc.js': 'icon-babel',
    '.babelrc.json': 'icon-babel',
    'makefile': 'icon-makefile',
    'gnumakefile': 'icon-makefile',
    'cmakefile': 'icon-cmake',
    'cmakelists.txt': 'icon-cmake',

    // ── Test ─────────────────────────────────────────────────────────────
    'jest.config.js': 'icon-jest',
    'jest.config.ts': 'icon-jest',
    'jest.config.mjs': 'icon-jest',
    'jest.config.cjs': 'icon-jest',
    'jest.setup.js': 'icon-jest',
    'jest.setup.ts': 'icon-jest',
    'vitest.config.js': 'icon-vitest',
    'vitest.config.ts': 'icon-vitest',
    'vitest.config.mjs': 'icon-vitest',
    'playwright.config.js': 'icon-playwright',
    'playwright.config.ts': 'icon-playwright',
    'cypress.config.js': 'icon-cypress',
    'cypress.config.ts': 'icon-cypress',
    'mocha.opts': 'icon-mocha',

    // ── CSS Frameworks ───────────────────────────────────────────────────
    'tailwind.config.js': 'icon-tailwind',
    'tailwind.config.ts': 'icon-tailwind',
    'tailwind.config.cjs': 'icon-tailwind',
    'tailwind.config.mjs': 'icon-tailwind',
    'postcss.config.js': 'icon-postcss-config',
    'postcss.config.cjs': 'icon-postcss-config',
    'postcss.config.mjs': 'icon-postcss-config',
    'uno.config.js': 'icon-unocss',
    'uno.config.ts': 'icon-unocss',

    // ── Framework Configs ────────────────────────────────────────────────
    'next.config.js': 'icon-next',
    'next.config.ts': 'icon-next',
    'next.config.mjs': 'icon-next',
    'nuxt.config.js': 'icon-nuxt',
    'nuxt.config.ts': 'icon-nuxt',
    'svelte.config.js': 'icon-svelte',
    'svelte.config.ts': 'icon-svelte',
    'astro.config.js': 'icon-astro',
    'astro.config.ts': 'icon-astro',
    'astro.config.mjs': 'icon-astro',
    'gatsby-config.js': 'icon-gatsby',
    'gatsby-config.ts': 'icon-gatsby',
    'remix.config.js': 'icon-remix',
    'remix.config.ts': 'icon-remix',
    'app.json': 'icon-expo',
    'expo.json': 'icon-expo',
    'capacitor.config.json': 'icon-capacitor',
    'capacitor.config.ts': 'icon-capacitor',
    'electron-builder.json': 'icon-electron',
    'electron-builder.yml': 'icon-electron',
    'electron.vite.config.js': 'icon-electron',
    'tauri.conf.json': 'icon-tauri',

    // ── Docker ───────────────────────────────────────────────────────────
    'dockerfile': 'icon-dockerfile',
    '.dockerignore': 'icon-dockerignore',
    'docker-compose.yml': 'icon-docker-compose',
    'docker-compose.yaml': 'icon-docker-compose',
    'docker-compose.override.yml': 'icon-docker-compose',

    // ── CI/CD ────────────────────────────────────────────────────────────
    '.travis.yml': 'icon-travis',
    '.travis.yaml': 'icon-travis',
    '.circleci': 'icon-circle-ci',
    'jenkinsfile': 'icon-jenkins',
    '.gitlab-ci.yml': 'icon-gitlab-ci',
    'sonar-project.properties': 'icon-sonar',
    '.sonarcloud.properties': 'icon-sonar',

    // ── Terraform / Infra ────────────────────────────────────────────────
    'vagrantfile': 'icon-vagrantfile',
    'procfile': 'icon-procfile',

    // ── Python ───────────────────────────────────────────────────────────
    'requirements.txt': 'icon-pip',
    'requirements-dev.txt': 'icon-pip',
    'setup.py': 'icon-python',
    'setup.cfg': 'icon-python',
    'pyproject.toml': 'icon-python',
    'pipfile': 'icon-pip',
    'pipfile.lock': 'icon-pip',

    // ── Ruby ─────────────────────────────────────────────────────────────
    'gemfile': 'icon-gemfile',
    'gemfile.lock': 'icon-gemfile',
    'rakefile': 'icon-ruby',

    // ── PHP ──────────────────────────────────────────────────────────────
    'composer.json': 'icon-composer',
    'composer.lock': 'icon-composer',

    // ── Java / Kotlin / Scala ────────────────────────────────────────────
    'pom.xml': 'icon-maven',
    'build.gradle': 'icon-gradle',
    'build.gradle.kts': 'icon-gradle',
    'settings.gradle': 'icon-gradle',
    'settings.gradle.kts': 'icon-gradle',
    'gradlew': 'icon-gradle',

    // ── Rust ─────────────────────────────────────────────────────────────
    'cargo.toml': 'icon-cargo',
    'cargo.lock': 'icon-cargo',

    // ── Elixir / Mix ─────────────────────────────────────────────────────
    'mix.exs': 'icon-mix',
    'mix.lock': 'icon-mix',

    // ── Go ───────────────────────────────────────────────────────────────
    'go.mod': 'icon-go',
    'go.sum': 'icon-go',
    'go.work': 'icon-go',

    // ── Dart / Flutter ───────────────────────────────────────────────────
    'pubspec.yaml': 'icon-flutter',
    'pubspec.lock': 'icon-flutter',

    // ── Docs / Meta ──────────────────────────────────────────────────────
    'readme': 'icon-readme',
    'readme.md': 'icon-readme',
    'readme.txt': 'icon-readme',
    'readme.rst': 'icon-readme',
    'changelog': 'icon-changelog',
    'changelog.md': 'icon-changelog',
    'changelog.txt': 'icon-changelog',
    'contributing': 'icon-contributing',
    'contributing.md': 'icon-contributing',
    'license': 'icon-license',
    'license.md': 'icon-license',
    'license.txt': 'icon-license',
    'authors': 'icon-authors',
    'authors.md': 'icon-authors',
    'security.md': 'icon-security',
    'code_of_conduct.md': 'icon-code-of-conduct',

    // ── VS Code / JetBrains ──────────────────────────────────────────────
    '.vscodeignore': 'icon-vscodeignore',
    'extensions.json': 'icon-vscode',

    // ── Storybook ────────────────────────────────────────────────────────
    '.storybook': 'icon-storybook',

    // ── Prisma / GraphQL ─────────────────────────────────────────────────
    'schema.prisma': 'icon-prisma',
    'schema.graphql': 'icon-graphql',
    'schema.gql': 'icon-graphql',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Folder Names  (case-insensitive, exact match)
  // ──────────────────────────────────────────────────────────────────────────
  folderNames: {
    'src': 'icon-folder-src',
    'source': 'icon-folder-src',
    'dist': 'icon-folder-dist',
    'build': 'icon-folder-dist',
    'out': 'icon-folder-dist',
    'output': 'icon-folder-dist',
    'release': 'icon-folder-dist',
    'bin': 'icon-folder-dist',
    'node_modules': 'icon-folder-node',
    '.npm': 'icon-folder-node',
    'public': 'icon-folder-public',
    'static': 'icon-folder-public',
    'www': 'icon-folder-public',
    'assets': 'icon-folder-assets',
    'media': 'icon-folder-assets',
    'resources': 'icon-folder-assets',
    'images': 'icon-folder-images',
    'img': 'icon-folder-images',
    'photos': 'icon-folder-images',
    'pictures': 'icon-folder-images',
    'icons': 'icon-folder-icons',
    'icon': 'icon-folder-icons',
    'svgs': 'icon-folder-icons',
    'fonts': 'icon-folder-fonts',
    'font': 'icon-folder-fonts',
    'components': 'icon-folder-components',
    'component': 'icon-folder-components',
    'ui': 'icon-folder-components',
    'views': 'icon-folder-views',
    'view': 'icon-folder-views',
    'screens': 'icon-folder-views',
    'pages': 'icon-folder-pages',
    'page': 'icon-folder-pages',
    'layouts': 'icon-folder-layouts',
    'layout': 'icon-folder-layouts',
    'hooks': 'icon-folder-hooks',
    'hook': 'icon-folder-hooks',
    'composables': 'icon-folder-hooks',
    'context': 'icon-folder-context',
    'contexts': 'icon-folder-context',
    'store': 'icon-folder-store',
    'stores': 'icon-folder-store',
    'redux': 'icon-folder-store',
    'state': 'icon-folder-store',
    'utils': 'icon-folder-utils',
    'util': 'icon-folder-utils',
    'helpers': 'icon-folder-utils',
    'helper': 'icon-folder-helper',
    'lib': 'icon-folder-utils',
    'libs': 'icon-folder-utils',
    'types': 'icon-folder-types',
    'type': 'icon-folder-types',
    'typings': 'icon-folder-types',
    '@types': 'icon-folder-types',
    'interfaces': 'icon-folder-types',
    'config': 'icon-folder-config',
    'configs': 'icon-folder-config',
    'configuration': 'icon-folder-config',
    'settings': 'icon-folder-config',
    'test': 'icon-folder-test',
    'tests': 'icon-folder-test',
    '__tests__': 'icon-folder-test',
    'spec': 'icon-folder-test',
    'specs': 'icon-folder-test',
    'e2e': 'icon-folder-test',
    '__mocks__': 'icon-folder-mock',
    'mocks': 'icon-folder-mock',
    'mock': 'icon-folder-mock',
    'fixtures': 'icon-folder-mock',
    'docs': 'icon-folder-docs',
    'doc': 'icon-folder-docs',
    'documentation': 'icon-folder-docs',
    'scripts': 'icon-folder-scripts',
    'script': 'icon-folder-scripts',
    'tools': 'icon-folder-scripts',
    'api': 'icon-folder-api',
    'apis': 'icon-folder-api',
    'routes': 'icon-folder-routes',
    'route': 'icon-folder-routes',
    'router': 'icon-folder-routes',
    'features': 'icon-folder-features',
    'feature': 'icon-folder-features',
    'modules': 'icon-folder-features',
    'module': 'icon-folder-features',
    'core': 'icon-folder-core',
    'shared': 'icon-folder-core',
    'common': 'icon-folder-core',
    'services': 'icon-folder-services',
    'service': 'icon-folder-services',
    'providers': 'icon-folder-services',
    'models': 'icon-folder-models',
    'model': 'icon-folder-models',
    'entities': 'icon-folder-models',
    'schemas': 'icon-folder-models',
    'controllers': 'icon-folder-controllers',
    'controller': 'icon-folder-controllers',
    'handlers': 'icon-folder-controllers',
    'middleware': 'icon-folder-middleware',
    'middlewares': 'icon-folder-middleware',
    'plugins': 'icon-folder-plugin',
    'plugin': 'icon-folder-plugin',
    'extensions': 'icon-folder-plugin',
    'themes': 'icon-folder-themes',
    'theme': 'icon-folder-themes',
    'styles': 'icon-folder-themes',
    'i18n': 'icon-folder-i18n',
    'locales': 'icon-folder-i18n',
    'locale': 'icon-folder-i18n',
    'translations': 'icon-folder-i18n',
    'lang': 'icon-folder-i18n',
    'prisma': 'icon-folder-prisma',
    'graphql': 'icon-folder-graphql',
    '.github': 'icon-folder-github',
    '.git': 'icon-folder-git',
    '.vscode': 'icon-folder-vscode',
    '.idea': 'icon-folder-vscode',
    '.husky': 'icon-folder-git',
    'docker': 'icon-folder-docker',
    '.docker': 'icon-folder-docker',
    'k8s': 'icon-folder-ci',
    'kubernetes': 'icon-folder-ci',
    'terraform': 'icon-folder-ci',
    '.terraform': 'icon-folder-ci',
    'ci': 'icon-folder-ci',
    '.ci': 'icon-folder-ci',
    'android': 'icon-folder-android',
    'ios': 'icon-folder-ios',
    'server': 'icon-folder-server',
    'backend': 'icon-folder-server',
    'env': 'icon-folder-env',
    'environment': 'icon-folder-env',
    'environments': 'icon-folder-env',
    'temp': 'icon-folder-temp',
    'tmp': 'icon-folder-temp',
    '.temp': 'icon-folder-temp',
    '.tmp': 'icon-folder-temp',
    'cache': 'icon-folder-cache',
    '.cache': 'icon-folder-cache',
    'coverage': 'icon-folder-coverage',
    '.nyc_output': 'icon-folder-coverage',
    'logs': 'icon-folder-log',
    'log': 'icon-folder-log',
    'generated': 'icon-folder-gen',
    '__generated__': 'icon-folder-gen',
    'gen': 'icon-folder-gen',
    '.storybook': 'icon-folder-plugin',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // Language IDs  (Monaco editor language identifiers)
  // ──────────────────────────────────────────────────────────────────────────
  languageIds: {
    'javascript': 'icon-js',
    'javascriptreact': 'icon-jsx',
    'typescript': 'icon-ts',
    'typescriptreact': 'icon-tsx',
    'html': 'icon-html',
    'css': 'icon-css',
    'scss': 'icon-sass',
    'less': 'icon-less',
    'vue': 'icon-vue',
    'svelte': 'icon-svelte',
    'python': 'icon-python',
    'java': 'icon-java',
    'kotlin': 'icon-kotlin',
    'scala': 'icon-scala',
    'c': 'icon-c',
    'cpp': 'icon-cpp',
    'csharp': 'icon-csharp',
    'fsharp': 'icon-fsharp',
    'go': 'icon-go',
    'rust': 'icon-rust',
    'ruby': 'icon-ruby',
    'php': 'icon-php',
    'perl': 'icon-perl',
    'lua': 'icon-lua',
    'r': 'icon-r',
    'swift': 'icon-swift',
    'dart': 'icon-dart',
    'elixir': 'icon-elixir',
    'erlang': 'icon-erlang',
    'haskell': 'icon-haskell',
    'clojure': 'icon-clojure',
    'ocaml': 'icon-ocaml',
    'nim': 'icon-nim',
    'zig': 'icon-zig',
    'julia': 'icon-julia',
    'shellscript': 'icon-bash',
    'powershell': 'icon-powershell',
    'bat': 'icon-bat',
    'json': 'icon-json',
    'jsonc': 'icon-json',
    'yaml': 'icon-yaml',
    'toml': 'icon-toml',
    'xml': 'icon-xml',
    'graphql': 'icon-graphql',
    'sql': 'icon-sql',
    'markdown': 'icon-markdown',
    'mdx': 'icon-mdx',
    'plaintext': 'icon-txt',
    'wasm': 'icon-wasm',
    'dockerfile': 'icon-dockerfile',
    'prisma': 'icon-prisma',
    'terraform': 'icon-ci',
    'proto3': 'icon-proto',
    'makefile': 'icon-makefile',
    'ini': 'icon-ini',
    'diff': 'icon-diff',
    'latex': 'icon-tex',
    'bibtex': 'icon-tex',

    // ── Extra Languages / New Additions ──────────────────────────────────
    'abap': 'icon-abap',
    'aes': 'icon-aes',
    'apex': 'icon-apex',
    'ats': 'icon-ats',
    'azcli': 'icon-azure',
    'batch': 'icon-bat',
    'bicep': 'icon-bicep',
    'cameligo': 'icon-cameligo',
    'coffeescript': 'icon-coffee',
    'csp': 'icon-csp',
    'cypher': 'icon-cypher',
    'dax': 'icon-dax',
    'ecl': 'icon-ecl',
    'flow9': 'icon-flow',
    'handlebars': 'icon-handlebars',
    'lexon': 'icon-lexon',
    'liquid': 'icon-liquid',
    'mips': 'icon-mips',
    'm3': 'icon-m3',
    'mysql': 'icon-sql',
    'objective-c': 'icon-objc',
    'pascal': 'icon-pascal',
    'pascaligo': 'icon-pascaligo',
    'pla': 'icon-pla',
    'postgresql': 'icon-pgsql',
    'pq': 'icon-powerquery',
    'protobuf': 'icon-proto',
    'pug': 'icon-pug',
    'qsharp': 'icon-qsharp',
    'razor': 'icon-razor',
    'redis': 'icon-redis',
    'redshift': 'icon-redshift',
    'restructuredtext': 'icon-rst',
    'sass': 'icon-sass',
    'scheme': 'icon-scheme',
    'shell': 'icon-bash',
    'sb': 'icon-smallbasic',
    'sol': 'icon-solidity',
    'sparql': 'icon-sparql',
    'st': 'icon-st',
    'systemverilog': 'icon-systemverilog',
    'tcl': 'icon-tcl',
    'twig': 'icon-twig',
    'typespec': 'icon-typespec',
    'v': 'icon-v',
    'vb': 'icon-vb',
    'visualbasic': 'icon-vb',
    'wgsl': 'icon-wgsl',
  },
}

export default defaultThemeMap;