// src/core/extensionAPI/sandbox/createSandbox.ts
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as ReactJsxRuntime from 'react/jsx-runtime';
import { fs } from '@/core/fileSystem';

/**
 * Return structure generated by executing an extension module inside the evaluation wrapper.
 * Provides entry and teardown lifetime lifecycle functions.
 */
export interface SandboxResult {
  activate:   ((context?: any) => void | Promise<void>) | undefined;
  deactivate: (() => void | Promise<void>) | undefined;
}

const createModuleProxy = (moduleObj: any) => {
  const actualModule = moduleObj && moduleObj.default ? moduleObj.default : moduleObj;
  
  return new Proxy(actualModule, {
    get(target, prop) {
      if (prop === 'default') return actualModule;
      if (prop === '__esModule') return true;
      return target[prop];
    }
  });
};

/** * Allowed global external module bindings mapped inside the sandbox runtime.
 * Sharing React is CRITICAL so extensions can use @mscode/ui without crashing!
 */
const ALLOWED_MODULES: Record<string, unknown> = {
  'react': createModuleProxy(React),
  'react-dom': createModuleProxy(ReactDOM),
  'react/jsx-runtime': createModuleProxy(ReactJsxRuntime), 
};
/**
 * Generates an isolated dependency loading factory closure function.
 * Restricts module imports to verified extensions and the foundational host application interface.
 */
const createSafeRequire = (mscodeAPI: any) => (mod: string): unknown => {
  // Route '@mscode/api' directly to the main API object
  if (mod === '@mscode/api' || mod === 'mscode') {
    return mscodeAPI;
  }

  // Route '@mscode/ui' specifically to the UI sub-module
  if (mod === '@mscode/ui') {
    return mscodeAPI.ui; 
  }

  // Allow safe external modules (like 'react', 'react/jsx-runtime')
  if (ALLOWED_MODULES[mod]) {
    return ALLOWED_MODULES[mod];
  }

  throw new Error(`[Sandbox] 🚨 require('${mod}') is not permitted. Extensions must bundle external dependencies.`);
};

const base64ToUint8Array = (base64: string): Uint8Array => {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

/**
 * Intercepts, evaluates, and redirects outbound runtime resource network requests.
 * Evaluates requested target addresses; relative resource hits pointing back inside 
 * extension bounds bypass external network ports entirely and serve content 
 * directly out of localized application virtual tracking filesystem nodes.
 * * @param baseUrl Root validation address namespace assigned to individual extension runtimes.
 * @param storeDir Physical destination container reference tracking local assets inside storage pools.
 * @returns An isolated async fetch handler matching standard browser specifications.
 */
const createSafeFetch = (baseUrl: string, storeDir: string) => {
  return async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    let requestUrl = typeof input === 'string' ? input : input.toString();

    // Standardize sub-path pointers transforming them back to absolute system addresses
    if (requestUrl.startsWith('./')) {
      requestUrl = new URL(requestUrl.replace(/^\.\//, ''), baseUrl).href;
    } else if (!requestUrl.startsWith('http')) {
      requestUrl = new URL(requestUrl, baseUrl).href;
    }

    // ── INTERCEPTION ENGINE TIER ──
    // Checks if the derived destination points within local extension boundaries.
    // Diverts execution vectors down to core framework file systems rather than cloud endpoints.
    if (requestUrl.startsWith(baseUrl)) {
      const fileName = requestUrl.replace(baseUrl, '');
      //  Prevent double-slashes in path (e.g. ms-storage://dir//file.wasm)
      const cleanFileName = fileName.startsWith('/') ? fileName.slice(1) : fileName;
      const targetPath = `ms-storage://${storeDir}/${cleanFileName}`;
    
      try {
        const fileContent = await fs.readFile(targetPath);
        const isBinary = /\.(png|jpe?g|gif|webp|ico|msxt|zip|wasm)$/i.test(cleanFileName);
        let body: any = fileContent;
        
        if (isBinary) {
          body = base64ToUint8Array(fileContent);
        }
        
        // Precise Content-Type inference for WebAssembly and JSON
        let contentType = 'text/plain';
        if (cleanFileName.endsWith('.json')) contentType = 'application/json';
        else if (cleanFileName.endsWith('.wasm')) contentType = 'application/wasm';
        else if (cleanFileName.endsWith('.png')) contentType = 'image/png';
        
        return new Response(body, {
          status: 200,
          headers: { 'Content-Type': contentType }
        });
      } catch (e) {
        console.error(`[Sandbox:Fetch] Internal 404 resource breakdown: ${targetPath}`, e);
        return new Response('Not Found', { status: 404 });
      }
    }

    console.log(`[Sandbox:Fetch] Executing real network request: ${requestUrl}`);
    return fetch(requestUrl, init);
  };
};

const createScopedConsole = (extId: string) => ({
  ...console,
  log: (...args: any[]) => console.log(`[${extId}]`, ...args),
  warn: (...args: any[]) => console.warn(`[${extId}]`, ...args),
  error: (...args: any[]) => console.error(`[${extId}]`, ...args),
  info: (...args: any[]) => console.info(`[${extId}]`, ...args),
});

/**
 * Compiles and executes untrusted string code inside an isolated closure execution context.
 * Blocks dangerous browser globals by mapping them out as undefined arguments while explicitly
 * forwarding safe dependency injection pipelines and virtualized local resource network modules.
 * * @param code Raw javascript text extracted from source bundle files.
 * @param mscodeAPI The framework runtime interface abstraction exposed to external scripts.
 * @param baseUrl Evaluation validation domain namespace identifier block.
 * @param storeDir Targeted subdirectory tracking internal plugin storage arrays.
 * @returns Extracted execution hooks parsed out of evaluating custom plugin modules.
 */
export function executeSandboxed(
  code: string,
  mscodeAPI: unknown,
  baseUrl: string,
  storeDir: string,
  extId: string = 'Extension'
): SandboxResult {
  const moduleObj = { exports: {} as Record<string, unknown> };

  /** List of global variable strings containing context vectors masked out via shadow fields */
  const SHADOWED = [
    'window', 'document', 'globalThis', 'self',
    'top', 'parent', 'frames', 'opener', 'XMLHttpRequest', 'localStorage', 'sessionStorage'
  ] as const;

  // Compile code into a wrapped evaluation wrapper function context
  const wrapper = new Function(
    'mscode', 'require', 'module', 'exports', 'fetch', 'console', '__dirname', '__filename',
    ...SHADOWED,
    `"use strict";\n${code}\nreturn module.exports;`,
  );

  // Invoke block passing localized parameters and explicit undefined assignments to enforce shadowing rules
  const exported = wrapper(
    mscodeAPI,
    createSafeRequire(mscodeAPI),
    moduleObj,
    moduleObj.exports,
    createSafeFetch(baseUrl, storeDir),
    createScopedConsole(extId),
    storeDir,                     // __dirname
    `${storeDir}/extension.js`,   // __filename
    ...SHADOWED.map(() => undefined),
  ) as Record<string, unknown>;

  return {
    activate:   typeof exported.activate   === 'function' ? exported.activate   as any : undefined,
    deactivate: typeof exported.deactivate === 'function' ? exported.deactivate as any : undefined,
  };
}